#!/usr/bin/env python
'''
Compile, test, and/or publish the Nim tuples module.
'''
from argparse import ArgumentParser
from subprocess import call, Popen, PIPE

parser = ArgumentParser(description=__doc__)
parser.add_argument('command', help='"compile", "test", or "publish"')
command = parser.parse_args().command

nim_flags = ['--parallelBuild:1', '--warning[Deprecated]:off',
             '--verbosity:0', '--path:source']

if command == 'compile':
    call(['nim', 'c', '-r'] + nim_flags + ['source/tuples.nim'])
elif command == 'test':
    call(['nim', 'c', '-r'] + nim_flags + ['tests/test.nim'])
elif command == 'doc':
    call(['nim', 'doc', '-o:index.html'] + nim_flags + ['source/tuples.nim'])
elif command == 'publish':
    git_status = Popen(['git', 'status', '--porcelain'], stdout=PIPE)
    if len(git_status.stdout.read()) > 0:
        print("Publishing did not succeed:")
        call(['git', 'status'])
        exit()
    call(['nim', 'doc', '-o:index.html'] + nim_flags + ['source/tuples.nim'])
    call(['git', 'push'])
    call(['scp', 'index.html', 'mmcgill@vision.caltech.edu:public_html/tuples'])
    print("Publishing succeeded.")
else:
    parser.print_help()
