#!/usr/bin/env python
'''
Compile, test, and/or publish the Nim tuples module.
'''
from argparse import ArgumentParser
from subprocess import Popen, PIPE

DOC_SITE = 'mmcgill@vision.caltech.edu:public_html/tuples'
NIM_FLAGS = ('--parallelBuild:1 --warning[Deprecated]:off ' +
             '--verbosity:0 --path:source')

def sh(cmd, **options):
    return Popen(cmd, shell=True, **options)

parser = ArgumentParser(description=__doc__)
parser.add_argument('command', help='"compile", "test", or "publish"')
command = parser.parse_args().command

if command == 'compile':
    sh('nim c -r ' + NIM_FLAGS + ' source/*.nim')
elif command == 'test':
    sh('nim c -r ' + NIM_FLAGS + ' tests/*.nim')
elif command == 'doc':
    sh('nim doc -o:index.html ' + NIM_FLAGS + ' source/*.nim')
elif command == 'publish':
    git_status = sh('git status --porcelain', stdout=PIPE)
    if len(git_status.stdout.read()) > 0:
        print('Publishing did not succeed:')
        sh('git status')
        exit()
    sh('nim doc -o:index.html ' + NIM_FLAGS + ' source/*.nim')
    call('git push')
    call('scp index.html ' + DOC_SITE)
    print('Publishing succeeded.')
else:
    parser.print_help()
